# SPDX-FileCopyrightText: 2026 Helmholtz-Zentrum Dresden - Rossendorf e.V. (HZDR)
# SPDX-FileContributor: David Pape
#
# SPDX-License-Identifier: CC0-1.0

[build-system]
requires = ["setuptools >= 80.10.1", "setuptools-scm>=9.2.2"]
build-backend = "setuptools.build_meta"

[project]
name = "hermes-plugin-software-card"
dynamic = ["version"]
description = "HERMES curation plugin using the Software CaRD framework."
authors = [{ name = "David Pape", email = "d.pape@hzdr.de" }]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: Software Development :: Quality Assurance",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.11"
dependencies = [
    "hermes >= 0.10.0",
    "software-card-policies @ git+https://github.com/softwarepub/software-card-policies.git",
]

[project.entry-points]

[project.entry-points."hermes.curate"]
software_card = "hermes_plugin_software_card.curate:SoftwareCaRDCuratePlugin"

[project.entry-points."software_card.environment"]
github = "hermes_plugin_software_card.environment:GitHubActionsEnvironment"
gitlab = "hermes_plugin_software_card.environment:GitLabCIEnvironment"

[project.urls]
homepage = "https://github.com/softwarepub/hermes-plugin-software-card"
repository = "https://github.com/softwarepub/hermes-plugin-software-card.git"

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    "D",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "F",
    "FBT",
    "FIX",
    "G",
    "I",
    "ICN",
    "INP",
    "N",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "TRY",
    "UP",
    "YTT",
]
ignore = ["COM812"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.setuptools_scm]
